-- =====================================================================
-- Ideas Digitales | Tienda minorista y mayorista — Esquema (Supabase / PostgreSQL)
-- Cómo usarlo: Supabase > SQL Editor > New query, pegar TODO este archivo y pulsar Run.
-- Se puede volver a ejecutar: borra lo que exista y lo crea de nuevo
-- (las cuentas de usuario se conservan; el rol admin hay que volver a asignarlo).
-- =====================================================================

-- ---------- 0. Limpieza (incluye tablas de versiones anteriores) ----------
drop view     if exists categorias_con_total, resumen_asesores, ventas_por_sede cascade;
drop table    if exists pedido_detalle, pedidos, solicitudes_mayoristas cascade;
drop table    if exists asesores, directores, sedes cascade;
drop table    if exists productos, categorias, proveedores, empleados cascade;
drop table    if exists perfiles cascade;
drop function if exists es_admin() cascade;
drop function if exists crear_perfil_nuevo_usuario() cascade;
drop function if exists es_pedido_mayorista(jsonb) cascade;
drop function if exists validar_max_directores() cascade;
drop function if exists validar_max_asesores() cascade;
drop function if exists confirmar_pedido(integer, integer, jsonb) cascade;


-- ---------- 1. Catálogo ----------
-- "generated by default as identity" = autonumérico (como AUTO_INCREMENT de MySQL)

create table categorias (
    idcategoria  integer generated by default as identity primary key,
    nombre       text not null,
    descripcion  text,
    foto         text
);

create table productos (
    idproducto      integer generated by default as identity primary key,
    nombre          text not null,
    precio          numeric(10,2) not null check (precio >= 0),
    preciorebajado  numeric(10,2) check (preciorebajado >= 0),   -- null = sin rebaja
    imagenchica     text,                                        -- URL completa de la imagen
    idcategoria     integer not null references categorias(idcategoria)
);

create table proveedores (
    idproveedor     integer generated by default as identity primary key,
    nombreempresa   text not null,
    nombrecontacto  text,
    cargocontacto   text,
    direccion       text,
    ciudad          text,
    region          text,
    codigopostal    text,
    pais            text,
    telefono        text,
    fax             text
);

-- Cantidad de productos por categoría
create view categorias_con_total with (security_invoker = on) as
    select c.*, (select count(*) from productos p where p.idcategoria = c.idcategoria)::int as total
    from categorias c;


-- ---------- 2. Equipo comercial: sedes > directores de venta > asesores ----------

create table sedes (
    idsede     integer generated by default as identity primary key,
    nombre     text not null unique,
    direccion  text,
    distrito   text
);

create table directores (
    iddirector  integer generated by default as identity primary key,
    nombres     text not null check (length(trim(nombres)) >= 2),
    apellidos   text not null check (length(trim(apellidos)) >= 2),
    correo      text check (correo like '%_@_%._%'),
    foto        text,
    idsede      integer not null references sedes(idsede)
);

create table asesores (
    idasesor    integer generated by default as identity primary key,
    nombres     text not null check (length(trim(nombres)) >= 2),
    apellidos   text not null check (length(trim(apellidos)) >= 2),
    correo      text check (correo like '%_@_%._%'),
    foto        text,
    -- on delete restrict: no se puede borrar un director que todavía tiene asesores
    iddirector  integer not null references directores(iddirector) on delete restrict
);

-- Regla: máximo 3 directores de venta por sede
create function validar_max_directores() returns trigger language plpgsql as $$
begin
    if (select count(*) from directores
        where idsede = new.idsede and iddirector is distinct from new.iddirector) >= 3 then
        raise exception 'La sede ya tiene 3 directores de venta (es el máximo).';
    end if;
    return new;
end;
$$;
create trigger max_directores_por_sede before insert or update of idsede on directores
    for each row execute function validar_max_directores();

-- Regla: máximo 10 asesores comerciales en total
create function validar_max_asesores() returns trigger language plpgsql as $$
begin
    if (select count(*) from asesores) >= 10 then
        raise exception 'Ya hay 10 asesores comerciales (es el máximo).';
    end if;
    return new;
end;
$$;
create trigger max_asesores before insert on asesores
    for each row execute function validar_max_asesores();


-- ---------- 3. Usuarios y roles ----------
-- Supabase guarda las cuentas en auth.users; aquí va el rol: 'cliente' (por defecto) o 'admin'.

create table perfiles (
    id      uuid primary key references auth.users(id) on delete cascade,
    nombre  text,
    correo  text,
    rol     text not null default 'cliente' check (rol in ('cliente', 'admin'))
);

-- Cada vez que alguien se registra, se le crea su perfil como 'cliente'
create function crear_perfil_nuevo_usuario() returns trigger
language plpgsql security definer set search_path = public as $$
begin
    insert into perfiles (id, nombre, correo) values (new.id, new.raw_user_meta_data ->> 'nombre', new.email);
    return new;
end;
$$;
create trigger al_crear_usuario after insert on auth.users
    for each row execute function crear_perfil_nuevo_usuario();

-- Cuentas que ya existían antes de ejecutar este script
insert into perfiles (id, nombre, correo)
    select id, raw_user_meta_data ->> 'nombre', email from auth.users
    on conflict (id) do nothing;

-- ¿Quien hace la consulta es administrador?
create function es_admin() returns boolean
language sql stable security definer set search_path = public as $$
    select exists (select 1 from perfiles where id = auth.uid() and rol = 'admin');
$$;


-- ---------- 4. Ventas: pedidos y solicitudes mayoristas ----------

create table pedidos (
    idpedido   integer generated by default as identity primary key,
    idusuario  uuid not null references perfiles(id) on delete cascade,
    idsede     integer not null references sedes(idsede),
    idasesor   integer references asesores(idasesor) on delete set null,  -- solo pedidos mayoristas
    tipo       text not null check (tipo in ('minorista', 'mayorista')),
    total      numeric(12,2) not null default 0,
    estado     text not null default 'registrado' check (estado in ('registrado', 'entregado', 'anulado')),
    fecha      timestamptz not null default now()
);

create table pedido_detalle (
    idpedido    integer not null references pedidos(idpedido) on delete cascade,
    idproducto  integer not null references productos(idproducto),
    nombre      text not null,                     -- copia del nombre al momento de la compra
    precio      numeric(10,2) not null,            -- precio al momento de la compra
    cantidad    integer not null check (cantidad between 1 and 9999),
    subtotal    numeric(12,2) generated always as (precio * cantidad) stored,
    primary key (idpedido, idproducto)
);

-- Compra mayorista: cada producto con 12 unidades o más
create function es_pedido_mayorista(productos jsonb) returns boolean
language sql immutable as $$
    select jsonb_typeof(productos) = 'array'
       and jsonb_array_length(productos) > 0
       and (select bool_and((p ->> 'cantidad')::int >= 12) from jsonb_array_elements(productos) p);
$$;

create table solicitudes_mayoristas (
    idsolicitud  integer generated by default as identity primary key,
    idusuario    uuid not null default auth.uid() references perfiles(id) on delete cascade,
    idasesor     integer not null references asesores(idasesor) on delete cascade,
    productos    jsonb not null check (es_pedido_mayorista(productos)),  -- [{idproducto, nombre, precio, cantidad}]
    mensaje      text check (length(mensaje) <= 500),
    estado       text not null default 'pendiente' check (estado in ('pendiente', 'atendida')),
    fecha        timestamptz not null default now()
);

/* Registrar un pedido. Se hace con una función del servidor (y no con un insert desde la página)
   para que los precios y el total los calcule la base de datos: nadie puede cambiar el precio
   desde el navegador.
   p_productos: [{"idproducto": 1, "cantidad": 3}, ...]
   p_idasesor: solo para compras mayoristas; en ese caso la venta se registra en la sede del asesor. */
create function confirmar_pedido(p_idsede integer, p_idasesor integer, p_productos jsonb) returns integer
language plpgsql security definer set search_path = public as $$
declare
    v_idpedido  integer;
    v_sede      integer := p_idsede;
    v_mayorista boolean;
begin
    if auth.uid() is null then
        raise exception 'Inicia sesión para registrar tu pedido.';
    end if;
    if jsonb_typeof(p_productos) is distinct from 'array' or jsonb_array_length(p_productos) = 0 then
        raise exception 'El pedido no tiene productos.';
    end if;
    if exists (select 1 from jsonb_array_elements(p_productos) x
               where (x ->> 'cantidad')::int not between 1 and 9999) then
        raise exception 'Hay una cantidad no válida en el pedido.';
    end if;
    if exists (select 1 from jsonb_array_elements(p_productos) x
               left join productos p on p.idproducto = (x ->> 'idproducto')::int
               where p.idproducto is null) then
        raise exception 'Uno de los productos ya no existe.';
    end if;

    v_mayorista := exists (select 1 from jsonb_array_elements(p_productos) x where (x ->> 'cantidad')::int >= 12);

    if p_idasesor is not null then
        if not v_mayorista then
            raise exception 'Solo las compras mayoristas (12 o más unidades de un producto) se asignan a un asesor.';
        end if;
        select d.idsede into v_sede
        from asesores a join directores d on d.iddirector = a.iddirector
        where a.idasesor = p_idasesor;
        if v_sede is null then
            raise exception 'El asesor elegido no existe.';
        end if;
    end if;

    if not exists (select 1 from sedes where idsede = v_sede) then
        raise exception 'Elige una sede.';
    end if;

    insert into pedidos (idusuario, idsede, idasesor, tipo)
        values (auth.uid(), v_sede, p_idasesor, case when v_mayorista then 'mayorista' else 'minorista' end)
        returning idpedido into v_idpedido;

    -- precio actual del catálogo (el rebajado si existe)
    insert into pedido_detalle (idpedido, idproducto, nombre, precio, cantidad)
        select v_idpedido, p.idproducto, p.nombre, coalesce(nullif(p.preciorebajado, 0), p.precio),
               sum((x ->> 'cantidad')::int)
        from jsonb_array_elements(p_productos) x
        join productos p on p.idproducto = (x ->> 'idproducto')::int
        group by p.idproducto, p.nombre, p.preciorebajado, p.precio;

    update pedidos set total = (select sum(subtotal) from pedido_detalle where idpedido = v_idpedido)
        where idpedido = v_idpedido;

    return v_idpedido;
end;
$$;


-- ---------- 5. Indicadores para la intranet ----------
-- security_invoker: la vista respeta las reglas de seguridad de quien consulta
-- (el admin ve todo; un cliente solo vería sus propios pedidos).

create view resumen_asesores with (security_invoker = on) as
    select a.idasesor, a.nombres, a.apellidos, a.foto,
           d.iddirector, d.nombres || ' ' || d.apellidos as director,
           s.idsede, s.nombre as sede,
           (select count(*) from solicitudes_mayoristas sm where sm.idasesor = a.idasesor)::int as solicitudes,
           (select count(*) from pedidos p where p.idasesor = a.idasesor and p.estado <> 'anulado')::int as pedidos,
           coalesce((select sum(p.total) from pedidos p where p.idasesor = a.idasesor and p.estado <> 'anulado'), 0) as ventas
    from asesores a
    join directores d on d.iddirector = a.iddirector
    join sedes s on s.idsede = d.idsede;

create view ventas_por_sede with (security_invoker = on) as
    select s.idsede, s.nombre as sede,
           count(p.idpedido)::int as pedidos,
           coalesce(sum(p.total), 0) as ventas,
           coalesce(sum(p.total) filter (where p.tipo = 'minorista'), 0) as ventas_minoristas,
           coalesce(sum(p.total) filter (where p.tipo = 'mayorista'), 0) as ventas_mayoristas
    from sedes s
    left join pedidos p on p.idsede = s.idsede and p.estado <> 'anulado'
    group by s.idsede, s.nombre;


-- ---------- 6. Seguridad (Row Level Security) ----------
-- Las aplica el SERVIDOR: aunque alguien llame a la API directamente, no puede saltárselas.

alter table categorias             enable row level security;
alter table productos              enable row level security;
alter table proveedores            enable row level security;
alter table sedes                  enable row level security;
alter table directores             enable row level security;
alter table asesores               enable row level security;
alter table perfiles               enable row level security;
alter table pedidos                enable row level security;
alter table pedido_detalle         enable row level security;
alter table solicitudes_mayoristas enable row level security;

-- Catálogo y equipo comercial: cualquiera lee; solo el admin modifica
create policy "lectura publica" on categorias for select using (true);
create policy "solo admin"      on categorias for all using (es_admin()) with check (es_admin());
create policy "lectura publica" on productos  for select using (true);
create policy "solo admin"      on productos  for all using (es_admin()) with check (es_admin());
create policy "lectura publica" on sedes      for select using (true);
create policy "solo admin"      on sedes      for all using (es_admin()) with check (es_admin());
create policy "lectura publica" on directores for select using (true);
create policy "solo admin"      on directores for all using (es_admin()) with check (es_admin());
create policy "lectura publica" on asesores   for select using (true);
create policy "solo admin"      on asesores   for all using (es_admin()) with check (es_admin());

-- Proveedores: solo admin (incluso para leer)
create policy "solo admin" on proveedores for all using (es_admin()) with check (es_admin());

-- Perfiles: cada usuario ve el suyo; el admin ve todos. Nadie se cambia el rol desde la página.
create policy "ver mi perfil" on perfiles for select using (id = auth.uid() or es_admin());

-- Pedidos: cada cliente ve los suyos y el admin todos. Se crean solo con confirmar_pedido().
create policy "ver mis pedidos" on pedidos for select to authenticated
    using (idusuario = auth.uid() or es_admin());
create policy "admin actualiza" on pedidos for update to authenticated
    using (es_admin()) with check (es_admin());
create policy "ver detalle de mis pedidos" on pedido_detalle for select to authenticated
    using (exists (select 1 from pedidos p where p.idpedido = pedido_detalle.idpedido
                   and (p.idusuario = auth.uid() or es_admin())));

-- Solicitudes: el cliente crea las suyas; ve las suyas; el admin ve y atiende todas
create policy "crear mi solicitud" on solicitudes_mayoristas for insert to authenticated
    with check (idusuario = auth.uid());
create policy "ver mis solicitudes" on solicitudes_mayoristas for select to authenticated
    using (idusuario = auth.uid() or es_admin());
create policy "admin actualiza" on solicitudes_mayoristas for update to authenticated
    using (es_admin()) with check (es_admin());


-- ---------- 7. Permisos de la API ----------
-- anon = visitante sin cuenta, authenticated = usuario con sesión.
-- Las reglas del punto 6 siguen decidiendo QUÉ filas puede tocar cada uno.

grant usage on schema public to anon, authenticated;
grant select on categorias, productos, categorias_con_total, sedes, directores, asesores to anon, authenticated;
grant select, insert, update, delete on categorias, productos, proveedores, sedes, directores, asesores to authenticated;
grant select on perfiles, pedidos, pedido_detalle, resumen_asesores, ventas_por_sede to authenticated;
grant update (estado) on pedidos to authenticated;
grant select, insert, update on solicitudes_mayoristas to authenticated;
grant usage on all sequences in schema public to authenticated;

-- confirmar_pedido solo para usuarios con sesión
revoke execute on function confirmar_pedido(integer, integer, jsonb) from public, anon;
grant  execute on function confirmar_pedido(integer, integer, jsonb) to authenticated;
