-- =====================================================================
-- El Galpón del Costo (minorista y mayorista) — Esquema (Supabase / PostgreSQL)
-- Cómo usarlo: Supabase > SQL Editor > New query, pegar TODO este archivo y pulsar Run.
-- Se puede volver a ejecutar: borra lo que exista y lo crea de nuevo
-- (las cuentas de usuario se conservan; el rol admin hay que volver a asignarlo).
-- =====================================================================

-- ---------- 0. Limpieza (incluye tablas de versiones anteriores) ----------
drop view     if exists categorias_con_total, resumen_asesores, ventas_por_sede,
                        resumen_proveedores, productos_por_reponer, productos_admin cascade;
drop table    if exists pedido_detalle, pedidos, solicitudes_mayoristas, zonas_envio cascade;
drop table    if exists asesores, directores, sedes cascade;
drop table    if exists costos_productos, productos, categorias, proveedores, empleados cascade;
drop table    if exists perfiles cascade;
drop function if exists es_admin() cascade;
drop function if exists crear_perfil_nuevo_usuario() cascade;
drop function if exists es_pedido_mayorista(jsonb) cascade;
drop function if exists validar_max_directores() cascade;
drop function if exists validar_max_asesores() cascade;
drop function if exists confirmar_pedido(integer, integer, jsonb) cascade;
drop function if exists confirmar_pedido(jsonb, jsonb, integer, text) cascade;
drop function if exists cotizar_envio(integer, numeric) cascade;
drop function if exists pagar_pedido(integer, text) cascade;
drop function if exists devolver_stock_al_anular() cascade;


-- ---------- 1. Catálogo ----------
-- "generated by default as identity" = autonumérico (como AUTO_INCREMENT de MySQL)

create table categorias (
    idcategoria  integer generated by default as identity primary key,
    nombre       text not null,
    descripcion  text,
    foto         text
);

create table proveedores (
    idproveedor     integer generated by default as identity primary key,
    nombreempresa   text not null,
    nombrecontacto  text,
    cargocontacto   text,
    direccion       text,
    ciudad          text,
    region          text,
    codigopostal    text,
    pais            text,
    telefono        text,
    fax             text
);

create table productos (
    idproducto      integer generated by default as identity primary key,
    nombre          text not null,
    precio          numeric(10,2) not null check (precio >= 0),
    preciorebajado  numeric(10,2) check (preciorebajado >= 0),   -- null = sin rebaja
    imagenchica     text,                                        -- URL completa de la imagen
    idcategoria     integer not null references categorias(idcategoria),
    idproveedor     integer references proveedores(idproveedor) on delete set null,  -- null = sin proveedor
    costo           numeric(10,2) not null default 0 check (costo >= 0),  -- costo de compra (SIMULADO); solo lo ve el admin
    stock           integer not null default 0 check (stock >= 0),   -- unidades disponibles
    stock_minimo    integer not null default 20 check (stock_minimo >= 0)  -- por debajo: hay que reponer
);

-- Cantidad de productos por categoría
create view categorias_con_total with (security_invoker = on) as
    select c.*, (select count(*) from productos p where p.idcategoria = c.idcategoria)::int as total
    from categorias c;


-- ---------- 2. Equipo comercial: sedes > directores de venta > asesores ----------

create table sedes (
    idsede     integer generated by default as identity primary key,
    nombre     text not null unique,
    direccion  text,
    distrito   text
);

create table directores (
    iddirector  integer generated by default as identity primary key,
    nombres     text not null check (length(trim(nombres)) >= 2),
    apellidos   text not null check (length(trim(apellidos)) >= 2),
    correo      text check (correo like '%_@_%._%'),
    foto        text,
    idsede      integer not null references sedes(idsede)
);

create table asesores (
    idasesor    integer generated by default as identity primary key,
    nombres     text not null check (length(trim(nombres)) >= 2),
    apellidos   text not null check (length(trim(apellidos)) >= 2),
    correo      text check (correo like '%_@_%._%'),
    foto        text,
    -- on delete restrict: no se puede borrar un director que todavía tiene asesores
    iddirector  integer not null references directores(iddirector) on delete restrict
);

-- Regla: máximo 3 directores de venta por sede
create function validar_max_directores() returns trigger language plpgsql as $$
begin
    if (select count(*) from directores
        where idsede = new.idsede and iddirector is distinct from new.iddirector) >= 3 then
        raise exception 'La sede ya tiene 3 directores de venta (es el máximo).';
    end if;
    return new;
end;
$$;
create trigger max_directores_por_sede before insert or update of idsede on directores
    for each row execute function validar_max_directores();

-- Regla: máximo 10 asesores comerciales en total
create function validar_max_asesores() returns trigger language plpgsql as $$
begin
    if (select count(*) from asesores) >= 10 then
        raise exception 'Ya hay 10 asesores comerciales (es el máximo).';
    end if;
    return new;
end;
$$;
create trigger max_asesores before insert on asesores
    for each row execute function validar_max_asesores();


-- ---------- 3. Usuarios y roles ----------
-- Supabase guarda las cuentas en auth.users; aquí va el rol: 'cliente' (por defecto) o 'admin'.

create table perfiles (
    id      uuid primary key references auth.users(id) on delete cascade,
    nombre  text,
    correo  text,
    rol     text not null default 'cliente' check (rol in ('cliente', 'admin'))
);

-- Cada vez que alguien se registra, se le crea su perfil como 'cliente'
create function crear_perfil_nuevo_usuario() returns trigger
language plpgsql security definer set search_path = public as $$
begin
    insert into perfiles (id, nombre, correo) values (new.id, new.raw_user_meta_data ->> 'nombre', new.email);
    return new;
end;
$$;
create trigger al_crear_usuario after insert on auth.users
    for each row execute function crear_perfil_nuevo_usuario();

-- Cuentas que ya existían antes de ejecutar este script
insert into perfiles (id, nombre, correo)
    select id, raw_user_meta_data ->> 'nombre', email from auth.users
    on conflict (id) do nothing;

-- ¿Quien hace la consulta es administrador?
create function es_admin() returns boolean
language sql stable security definer set search_path = public as $$
    select exists (select 1 from perfiles where id = auth.uid() and rol = 'admin');
$$;


-- ---------- 4. Ventas: pedidos y solicitudes mayoristas ----------

-- Zonas de envío por departamento. costo null = el asesor cotiza (solo pedidos mayoristas)
create table zonas_envio (
    departamento  text primary key,
    zona          text not null check (zona in ('lima', 'cercana', 'alejada')),
    costo         numeric(10,2) check (costo >= 0),
    plazo         text not null
);

create table pedidos (
    idpedido     integer generated by default as identity primary key,
    idusuario    uuid not null references perfiles(id) on delete cascade,
    idsede       integer not null references sedes(idsede),       -- sede que atiende o despacha
    idasesor     integer references asesores(idasesor) on delete set null,  -- solo pedidos mayoristas
    tipo         text not null check (tipo in ('minorista', 'mayorista')),
    -- Entrega
    entrega      text not null default 'recojo' check (entrega in ('recojo', 'delivery')),
    departamento text references zonas_envio(departamento),
    distrito     text,
    direccion    text,
    referencia   text,
    telefono     text,
    plazo        text,                                            -- ej. "1 día", "3 a 5 días hábiles"
    -- Montos
    subtotal     numeric(12,2) not null default 0,                -- productos
    costo_envio  numeric(10,2),                                   -- null mientras está por cotizar
    total        numeric(12,2) not null default 0,                -- productos + envío
    -- Pago (simulado: solo se guarda el método, nunca datos de tarjeta)
    metodo_pago  text check (metodo_pago in ('tarjeta', 'yape')),
    pago_estado  text not null default 'pendiente' check (pago_estado in ('pendiente', 'pagado')),
    estado       text not null default 'registrado'
                 check (estado in ('por_cotizar', 'cotizado', 'registrado', 'entregado', 'anulado')),
    fecha        timestamptz not null default now()
);

create table pedido_detalle (
    idpedido    integer not null references pedidos(idpedido) on delete cascade,
    idproducto  integer not null references productos(idproducto),
    nombre      text not null,                     -- copia del nombre al momento de la compra
    precio      numeric(10,2) not null,            -- precio al momento de la compra
    costo       numeric(10,2) not null default 0,  -- costo al momento de la compra (para el margen)
    cantidad    integer not null check (cantidad between 1 and 9999),
    subtotal    numeric(12,2) generated always as (precio * cantidad) stored,
    margen      numeric(12,2) generated always as ((precio - costo) * cantidad) stored,
    primary key (idpedido, idproducto)
);

-- Compra mayorista: cada producto con 12 unidades o más
create function es_pedido_mayorista(productos jsonb) returns boolean
language sql immutable as $$
    select jsonb_typeof(productos) = 'array'
       and jsonb_array_length(productos) > 0
       and (select bool_and((p ->> 'cantidad')::int >= 12) from jsonb_array_elements(productos) p);
$$;

create table solicitudes_mayoristas (
    idsolicitud  integer generated by default as identity primary key,
    idusuario    uuid not null default auth.uid() references perfiles(id) on delete cascade,
    idasesor     integer not null references asesores(idasesor) on delete cascade,
    productos    jsonb not null check (es_pedido_mayorista(productos)),  -- [{idproducto, nombre, precio, cantidad}]
    mensaje      text check (length(mensaje) <= 500),
    estado       text not null default 'pendiente' check (estado in ('pendiente', 'atendida')),
    fecha        timestamptz not null default now()
);

/* Registrar un pedido. Se hace con una función del servidor (y no con un insert desde la página)
   para que precios, envío y total los calcule la base de datos: nadie puede cambiarlos desde el navegador.
   p_productos: [{"idproducto": 1, "cantidad": 3}, ...]
   p_entrega:   {"tipo": "recojo", "idsede": 1}
                {"tipo": "delivery", "departamento": "Ica", "distrito": "...", "direccion": "...",
                 "referencia": "...", "telefono": "987654321"}
   p_idasesor:  solo para compras mayoristas; la venta se registra en la sede del asesor.
   p_metodo_pago: 'tarjeta' o 'yape' (el pago es simulado). No se usa si el envío queda por cotizar.
   También descuenta (reserva) el stock; si no alcanza, rechaza el pedido completo. */
create function confirmar_pedido(p_productos jsonb, p_entrega jsonb, p_idasesor integer, p_metodo_pago text)
returns integer
language plpgsql security definer set search_path = public as $$
declare
    v_idpedido   integer;
    v_mayorista  boolean;
    v_falta      record;
    v_tipo       text := p_entrega ->> 'tipo';
    v_sede       integer;
    v_zona       record;
    v_envio      numeric(10,2) := 0;
    v_estado     text := 'registrado';
    v_depto      text;           -- datos de la zona (solo para delivery)
    v_plazo      text;
begin
    if auth.uid() is null then
        raise exception 'Inicia sesión para registrar tu pedido.';
    end if;
    if jsonb_typeof(p_productos) is distinct from 'array' or jsonb_array_length(p_productos) = 0 then
        raise exception 'El pedido no tiene productos.';
    end if;
    if exists (select 1 from jsonb_array_elements(p_productos) x
               where (x ->> 'cantidad')::int not between 1 and 9999) then
        raise exception 'Hay una cantidad no válida en el pedido.';
    end if;
    if exists (select 1 from jsonb_array_elements(p_productos) x
               left join productos p on p.idproducto = (x ->> 'idproducto')::int
               where p.idproducto is null) then
        raise exception 'Uno de los productos ya no existe.';
    end if;

    -- Stock: "for update" bloquea esas filas hasta terminar, así dos compras a la vez
    -- no pueden vender la misma unidad
    perform 1 from productos
        where idproducto in (select (x ->> 'idproducto')::int from jsonb_array_elements(p_productos) x)
        for update;
    select p.nombre, p.stock into v_falta
        from (select (x ->> 'idproducto')::int as idproducto, sum((x ->> 'cantidad')::int) as cantidad
              from jsonb_array_elements(p_productos) x group by 1) pedido
        join productos p using (idproducto)
        where pedido.cantidad > p.stock
        limit 1;
    if found then
        raise exception 'No hay stock suficiente de "%": quedan % unidades.', v_falta.nombre, v_falta.stock;
    end if;

    v_mayorista := exists (select 1 from jsonb_array_elements(p_productos) x where (x ->> 'cantidad')::int >= 12);

    -- Asesor (solo mayorista): la venta queda en su sede
    if p_idasesor is not null then
        if not v_mayorista then
            raise exception 'Solo las compras mayoristas (12 o más unidades de un producto) se asignan a un asesor.';
        end if;
        select d.idsede into v_sede
        from asesores a join directores d on d.iddirector = a.iddirector
        where a.idasesor = p_idasesor;
        if v_sede is null then
            raise exception 'El asesor elegido no existe.';
        end if;
    end if;

    -- Entrega
    if v_tipo = 'recojo' then
        if v_sede is null then
            v_sede := (p_entrega ->> 'idsede')::int;
        end if;
        if not exists (select 1 from sedes where idsede = v_sede) then
            raise exception 'Elige la sede donde recogerás tu pedido.';
        end if;
    elsif v_tipo = 'delivery' then
        select * into v_zona from zonas_envio where departamento = p_entrega ->> 'departamento';
        if not found then
            raise exception 'Elige un departamento de envío válido.';
        end if;
        v_depto := v_zona.departamento;
        v_plazo := v_zona.plazo;
        if length(trim(coalesce(p_entrega ->> 'direccion', ''))) < 5 or length(trim(coalesce(p_entrega ->> 'distrito', ''))) < 3 then
            raise exception 'Completa el distrito y la dirección de entrega.';
        end if;
        if coalesce(p_entrega ->> 'telefono', '') !~ '^9[0-9]{8}$' then
            raise exception 'El teléfono debe ser un celular de 9 dígitos que empiece con 9.';
        end if;
        if v_zona.zona = 'alejada' then
            if not v_mayorista or p_idasesor is null then
                raise exception 'El envío a % solo está disponible para compras mayoristas con un asesor, que cotiza el envío.', v_zona.departamento;
            end if;
            v_envio  := null;
            v_estado := 'por_cotizar';
        else
            v_envio := v_zona.costo;
        end if;
        if v_sede is null then   -- sin asesor: despacha el galpón del Callao
            select idsede into v_sede from sedes where nombre = 'Callao';
        end if;
    else
        raise exception 'Elige recojo en sede o delivery.';
    end if;

    -- Pago (salvo que el envío esté por cotizar)
    if v_estado <> 'por_cotizar' and coalesce(p_metodo_pago, '') not in ('tarjeta', 'yape') then
        raise exception 'Elige un método de pago: tarjeta o Yape.';
    end if;

    insert into pedidos (idusuario, idsede, idasesor, tipo, entrega, departamento, distrito, direccion,
                         referencia, telefono, plazo, costo_envio, metodo_pago, pago_estado, estado)
        values (auth.uid(), v_sede, p_idasesor, case when v_mayorista then 'mayorista' else 'minorista' end,
                v_tipo,
                v_depto,
                case when v_tipo = 'delivery' then trim(p_entrega ->> 'distrito') end,
                case when v_tipo = 'delivery' then trim(p_entrega ->> 'direccion') end,
                case when v_tipo = 'delivery' then nullif(trim(p_entrega ->> 'referencia'), '') end,
                case when v_tipo = 'delivery' then p_entrega ->> 'telefono' end,
                v_plazo,
                v_envio,
                case when v_estado = 'por_cotizar' then null else p_metodo_pago end,
                case when v_estado = 'por_cotizar' then 'pendiente' else 'pagado' end,
                v_estado)
        returning idpedido into v_idpedido;

    -- precio actual del catálogo (el rebajado si existe)
    insert into pedido_detalle (idpedido, idproducto, nombre, precio, costo, cantidad)
        select v_idpedido, p.idproducto, p.nombre, coalesce(nullif(p.preciorebajado, 0), p.precio),
               p.costo, sum((x ->> 'cantidad')::int)
        from jsonb_array_elements(p_productos) x
        join productos p on p.idproducto = (x ->> 'idproducto')::int
        group by p.idproducto, p.nombre, p.preciorebajado, p.precio, p.costo;

    update productos p set stock = p.stock - d.cantidad
        from pedido_detalle d
        where d.idpedido = v_idpedido and d.idproducto = p.idproducto;

    update pedidos
        set subtotal = (select sum(subtotal) from pedido_detalle where idpedido = v_idpedido),
            total    = (select sum(subtotal) from pedido_detalle where idpedido = v_idpedido) + coalesce(v_envio, 0)
        where idpedido = v_idpedido;

    return v_idpedido;
end;
$$;

/* El admin (asesor) pone el costo de envío de un pedido "por cotizar" */
create function cotizar_envio(p_idpedido integer, p_costo numeric) returns void
language plpgsql security definer set search_path = public as $$
begin
    if not es_admin() then
        raise exception 'Solo un administrador puede cotizar envíos.';
    end if;
    if p_costo is null or p_costo < 0 or p_costo > 5000 then
        raise exception 'Ingresa un costo de envío válido.';
    end if;
    update pedidos set costo_envio = p_costo, total = subtotal + p_costo, estado = 'cotizado'
        where idpedido = p_idpedido and estado = 'por_cotizar';
    if not found then
        raise exception 'El pedido no existe o ya no está por cotizar.';
    end if;
end;
$$;

/* El cliente paga (simulado) un pedido ya cotizado */
create function pagar_pedido(p_idpedido integer, p_metodo_pago text) returns void
language plpgsql security definer set search_path = public as $$
begin
    if coalesce(p_metodo_pago, '') not in ('tarjeta', 'yape') then
        raise exception 'Elige un método de pago: tarjeta o Yape.';
    end if;
    update pedidos set metodo_pago = p_metodo_pago, pago_estado = 'pagado', estado = 'registrado'
        where idpedido = p_idpedido and idusuario = auth.uid() and estado = 'cotizado';
    if not found then
        raise exception 'Este pedido no está pendiente de pago.';
    end if;
end;
$$;


-- ---------- 5. Indicadores para la intranet ----------
-- security_invoker: la vista respeta las reglas de seguridad de quien consulta
-- (el admin ve todo; un cliente solo vería sus propios pedidos).

create view resumen_asesores with (security_invoker = on) as
    select a.idasesor, a.nombres, a.apellidos, a.foto,
           d.iddirector, d.nombres || ' ' || d.apellidos as director,
           s.idsede, s.nombre as sede,
           (select count(*) from solicitudes_mayoristas sm where sm.idasesor = a.idasesor)::int as solicitudes,
           (select count(*) from pedidos p where p.idasesor = a.idasesor
                and p.estado <> 'anulado' and p.pago_estado = 'pagado')::int as pedidos,
           coalesce((select sum(p.subtotal) from pedidos p where p.idasesor = a.idasesor
                and p.estado <> 'anulado' and p.pago_estado = 'pagado'), 0) as ventas
    from asesores a
    join directores d on d.iddirector = a.iddirector
    join sedes s on s.idsede = d.idsede;

-- ventas_por_sede y resumen_proveedores usan el COSTO (margen), que los clientes no pueden leer.
-- Por eso se ejecutan con permisos del dueño de la vista y solo devuelven filas al admin.
create view ventas_por_sede as
    select s.idsede, s.nombre as sede,
           count(p.idpedido)::int as pedidos,
           coalesce(sum(p.subtotal), 0) as ventas,
           coalesce(sum(p.subtotal) filter (where p.tipo = 'minorista'), 0) as ventas_minoristas,
           coalesce(sum(p.subtotal) filter (where p.tipo = 'mayorista'), 0) as ventas_mayoristas,
           coalesce(sum((select sum(d.margen) from pedido_detalle d where d.idpedido = p.idpedido)), 0) as margen
    from sedes s
    left join pedidos p on p.idsede = s.idsede and p.estado <> 'anulado' and p.pago_estado = 'pagado'
    where es_admin()
    group by s.idsede, s.nombre;


-- Si el admin anula un pedido, las unidades vuelven al stock
create function devolver_stock_al_anular() returns trigger language plpgsql as $$
begin
    if new.estado = 'anulado' and old.estado <> 'anulado' then
        update productos p set stock = p.stock + d.cantidad
            from pedido_detalle d
            where d.idpedido = new.idpedido and d.idproducto = p.idproducto;
    end if;
    return new;
end;
$$;
create trigger al_anular_pedido after update of estado on pedidos
    for each row execute function devolver_stock_al_anular();

-- Proveedores: cuántos productos aportan, cuánto se vendió de ellos y qué margen dejan
create view resumen_proveedores as
    select v.idproveedor, v.nombreempresa, v.nombrecontacto, v.cargocontacto, v.telefono, v.ciudad, v.pais,
           (select count(*) from productos p where p.idproveedor = v.idproveedor)::int as productos,
           (select count(*) from productos p where p.idproveedor = v.idproveedor and p.stock <= p.stock_minimo)::int as por_reponer,
           coalesce(sum(d.cantidad), 0)::int as unidades_vendidas,
           coalesce(sum(d.subtotal), 0) as ventas,
           coalesce(sum(d.margen), 0) as margen
    from proveedores v
    left join productos p on p.idproveedor = v.idproveedor
    left join pedido_detalle d on d.idproducto = p.idproducto
         and exists (select 1 from pedidos x where x.idpedido = d.idpedido
                     and x.estado <> 'anulado' and x.pago_estado = 'pagado')
    where es_admin()
    group by v.idproveedor;

-- Catálogo completo CON costo y ganancia unitaria, solo para el admin.
-- (Esta vista se ejecuta con permisos de su dueño y filtra con es_admin(): un cliente recibe 0 filas.)
create view productos_admin as
    select p.*,
           coalesce(nullif(p.preciorebajado, 0), p.precio) as precio_final,
           coalesce(nullif(p.preciorebajado, 0), p.precio) - p.costo as ganancia_unitaria
    from productos p
    where es_admin();

-- Productos con stock en el mínimo o por debajo, con el proveedor a quien pedirlos
create view productos_por_reponer with (security_invoker = on) as
    select p.idproducto, p.nombre, p.stock, p.stock_minimo,
           v.idproveedor, v.nombreempresa, v.nombrecontacto, v.telefono, v.pais
    from productos p
    left join proveedores v on v.idproveedor = p.idproveedor
    where p.stock <= p.stock_minimo;


-- ---------- 6. Seguridad (Row Level Security) ----------
-- Las aplica el SERVIDOR: aunque alguien llame a la API directamente, no puede saltárselas.

alter table categorias             enable row level security;
alter table productos              enable row level security;
alter table proveedores            enable row level security;
alter table sedes                  enable row level security;
alter table directores             enable row level security;
alter table asesores               enable row level security;
alter table perfiles               enable row level security;
alter table pedidos                enable row level security;
alter table zonas_envio            enable row level security;
alter table pedido_detalle         enable row level security;
alter table solicitudes_mayoristas enable row level security;

-- Catálogo y equipo comercial: cualquiera lee; solo el admin modifica
create policy "lectura publica" on categorias for select using (true);
create policy "solo admin"      on categorias for all using (es_admin()) with check (es_admin());
create policy "lectura publica" on productos  for select using (true);
create policy "solo admin"      on productos  for all using (es_admin()) with check (es_admin());
create policy "lectura publica" on sedes      for select using (true);
create policy "solo admin"      on sedes      for all using (es_admin()) with check (es_admin());
create policy "lectura publica" on directores for select using (true);
create policy "solo admin"      on directores for all using (es_admin()) with check (es_admin());
create policy "lectura publica" on asesores   for select using (true);
create policy "solo admin"      on asesores   for all using (es_admin()) with check (es_admin());

-- Zonas de envío: cualquiera las lee (para calcular el envío en la página); solo el admin las cambia
create policy "lectura publica" on zonas_envio for select using (true);
create policy "solo admin"      on zonas_envio for all using (es_admin()) with check (es_admin());

-- Proveedores: solo admin (incluso para leer)
create policy "solo admin" on proveedores for all using (es_admin()) with check (es_admin());

-- Perfiles: cada usuario ve el suyo; el admin ve todos. Nadie se cambia el rol desde la página.
create policy "ver mi perfil" on perfiles for select using (id = auth.uid() or es_admin());

-- Pedidos: cada cliente ve los suyos y el admin todos. Se crean solo con confirmar_pedido().
create policy "ver mis pedidos" on pedidos for select to authenticated
    using (idusuario = auth.uid() or es_admin());
create policy "admin actualiza" on pedidos for update to authenticated
    using (es_admin()) with check (es_admin());
create policy "ver detalle de mis pedidos" on pedido_detalle for select to authenticated
    using (exists (select 1 from pedidos p where p.idpedido = pedido_detalle.idpedido
                   and (p.idusuario = auth.uid() or es_admin())));

-- Solicitudes: el cliente crea las suyas; ve las suyas; el admin ve y atiende todas
create policy "crear mi solicitud" on solicitudes_mayoristas for insert to authenticated
    with check (idusuario = auth.uid());
create policy "ver mis solicitudes" on solicitudes_mayoristas for select to authenticated
    using (idusuario = auth.uid() or es_admin());
create policy "admin actualiza" on solicitudes_mayoristas for update to authenticated
    using (es_admin()) with check (es_admin());


-- ---------- 7. Permisos de la API ----------
-- anon = visitante sin cuenta, authenticated = usuario con sesión.
-- Las reglas del punto 6 siguen decidiendo QUÉ filas puede tocar cada uno.

grant usage on schema public to anon, authenticated;
grant select on categorias, categorias_con_total, sedes, directores, asesores, zonas_envio to anon, authenticated;
-- productos: se pueden leer todas las columnas MENOS costo (permiso por columna)
grant select (idproducto, nombre, precio, preciorebajado, imagenchica, idcategoria, idproveedor, stock, stock_minimo)
    on productos to anon, authenticated;
grant insert, update, delete on productos to authenticated;
grant select, insert, update, delete on categorias, proveedores, sedes, directores, asesores to authenticated;
grant select on productos_admin to authenticated;
-- pedido_detalle: el cliente ve sus productos, precios y cantidades, pero NO costo ni margen
grant select (idpedido, idproducto, nombre, precio, cantidad, subtotal) on pedido_detalle to authenticated;
grant select on perfiles, pedidos, resumen_asesores, ventas_por_sede,
                resumen_proveedores, productos_por_reponer to authenticated;
grant update (estado) on pedidos to authenticated;
grant select, insert, update on solicitudes_mayoristas to authenticated;
grant usage on all sequences in schema public to authenticated;

-- Funciones de compra solo para usuarios con sesión (cotizar_envio además revisa que sea admin)
revoke execute on function confirmar_pedido(jsonb, jsonb, integer, text) from public, anon;
grant  execute on function confirmar_pedido(jsonb, jsonb, integer, text) to authenticated;
revoke execute on function cotizar_envio(integer, numeric) from public, anon;
grant  execute on function cotizar_envio(integer, numeric) to authenticated;
revoke execute on function pagar_pedido(integer, text) from public, anon;
grant  execute on function pagar_pedido(integer, text) to authenticated;
