-- =====================================================================
-- Ideas Digitales | Tienda — Esquema de la base de datos (Supabase / PostgreSQL)
-- Cómo usarlo: en Supabase > SQL Editor > New query, pega TODO este archivo y pulsa Run.
-- Se puede volver a ejecutar: primero borra lo que exista y lo crea de nuevo.
-- =====================================================================

-- ---------- 0. Limpieza (para poder ejecutar el script más de una vez) ----------
drop view     if exists categorias_con_total;
drop table    if exists productos   cascade;
drop table    if exists categorias  cascade;
drop table    if exists directores  cascade;
drop table    if exists proveedores cascade;
drop table    if exists empleados   cascade;
drop table    if exists perfiles    cascade;
drop function if exists es_admin() cascade;
drop function if exists crear_perfil_nuevo_usuario() cascade;


-- ---------- 1. Tablas del catálogo ----------
-- "generated by default as identity" = autonumérico (como AUTO_INCREMENT de MySQL)

create table categorias (
    idcategoria  integer generated by default as identity primary key,
    nombre       text not null,
    descripcion  text,
    foto         text
);

create table productos (
    idproducto      integer generated by default as identity primary key,
    nombre          text not null,
    precio          numeric(10,2) not null check (precio >= 0),
    preciorebajado  numeric(10,2) check (preciorebajado >= 0),   -- null = sin rebaja
    imagenchica     text,                                        -- URL completa de la imagen
    idcategoria     integer not null references categorias(idcategoria)
);

create table directores (
    iddirector  integer generated by default as identity primary key,
    nombres     text not null check (length(trim(nombres)) >= 4),
    peliculas   text not null check (length(trim(peliculas)) >= 6)
);

create table proveedores (
    idproveedor     integer generated by default as identity primary key,
    nombreempresa   text not null,
    nombrecontacto  text,
    cargocontacto   text,
    direccion       text,
    ciudad          text,
    region          text,
    codigopostal    text,
    pais            text,
    telefono        text,
    fax             text
);

-- Solo los datos públicos que muestra la página (sin sueldos, claves ni datos personales)
create table empleados (
    idempleado  integer generated by default as identity primary key,
    nombres     text not null,
    apellidos   text not null,
    cargo       text,
    foto        text
);

-- Cantidad de productos por categoría (lo que antes devolvía el campo "total")
create view categorias_con_total with (security_invoker = on) as
    select c.*, (select count(*) from productos p where p.idcategoria = c.idcategoria)::int as total
    from categorias c;


-- ---------- 2. Usuarios y roles ----------
-- Supabase guarda las cuentas (correo y contraseña) en auth.users.
-- Aquí guardamos el rol de cada cuenta: 'cliente' (por defecto) o 'admin'.

create table perfiles (
    id      uuid primary key references auth.users(id) on delete cascade,
    nombre  text,
    rol     text not null default 'cliente' check (rol in ('cliente', 'admin'))
);

-- Cada vez que alguien se registra, se le crea su perfil como 'cliente'
create function crear_perfil_nuevo_usuario() returns trigger
language plpgsql security definer set search_path = public as $$
begin
    insert into perfiles (id, nombre) values (new.id, new.raw_user_meta_data ->> 'nombre');
    return new;
end;
$$;

create trigger al_crear_usuario
    after insert on auth.users
    for each row execute function crear_perfil_nuevo_usuario();

-- ¿La persona que hace la consulta es administrador?
create function es_admin() returns boolean
language sql stable security definer set search_path = public as $$
    select exists (select 1 from perfiles where id = auth.uid() and rol = 'admin');
$$;


-- ---------- 3. Seguridad (Row Level Security) ----------
-- Estas reglas las aplica el SERVIDOR: aunque alguien llame a la API directamente,
-- solo un admin puede insertar, actualizar o eliminar.

alter table categorias  enable row level security;
alter table productos   enable row level security;
alter table directores  enable row level security;
alter table proveedores enable row level security;
alter table empleados   enable row level security;
alter table perfiles    enable row level security;

-- Catálogo: cualquiera puede leer; solo el admin puede modificar
create policy "lectura publica"  on categorias  for select using (true);
create policy "solo admin"       on categorias  for all using (es_admin()) with check (es_admin());
create policy "lectura publica"  on productos   for select using (true);
create policy "solo admin"       on productos   for all using (es_admin()) with check (es_admin());
create policy "lectura publica"  on directores  for select using (true);
create policy "solo admin"       on directores  for all using (es_admin()) with check (es_admin());
create policy "lectura publica"  on proveedores for select using (true);
create policy "solo admin"       on proveedores for all using (es_admin()) with check (es_admin());
create policy "lectura publica"  on empleados   for select using (true);
create policy "solo admin"       on empleados   for all using (es_admin()) with check (es_admin());

-- Perfiles: cada usuario ve solo el suyo (el admin ve todos). Nadie puede cambiarse el rol desde la página.
create policy "ver mi perfil" on perfiles for select using (id = auth.uid() or es_admin());


-- ---------- 4. Permisos de la API ----------
-- anon = visitante sin cuenta, authenticated = usuario con sesión iniciada.
-- Se dan explícitamente para que funcione aunque el proyecto no "exponga" tablas automáticamente.
-- Las reglas del punto 3 siguen decidiendo QUÉ filas puede tocar cada uno.

grant usage on schema public to anon, authenticated;
grant select on categorias, productos, directores, proveedores, empleados, categorias_con_total
    to anon, authenticated;
grant insert, update, delete on categorias, productos, directores, proveedores, empleados
    to authenticated;
grant select on perfiles to authenticated;
grant usage on all sequences in schema public to authenticated;
