-- =====================================================================
-- Ideas Digitales | Tienda — Cambios de la Fase 6b
--   * Proveedores pasa a ser solo para administradores
--   * Asesores comerciales (empleados marcados con es_asesor)
--   * Solicitudes de compra mayorista (12 o más unidades por producto)
-- Ejecutar DESPUÉS de 01_esquema.sql y 02_datos.sql, en Supabase > SQL Editor.
-- Se puede volver a ejecutar sin problema.
-- =====================================================================

-- ---------- 1. Proveedores: solo admin ----------
-- Se quita la lectura pública; queda la regla "solo admin" (que incluye leer).
drop policy if exists "lectura publica" on proveedores;
revoke select on proveedores from anon;


-- ---------- 2. Asesores comerciales ----------
alter table empleados add column if not exists es_asesor boolean not null default false;

-- Los que atienden ventas a empresas
update empleados set es_asesor = (idempleado in (1, 9, 15, 18));
--   1  Alexander Skarsgård  - Supervisor de Ventas Corporativas (B2B)
--   9  Joan Smalls          - Gerente Comercial
--  15  Nicholas Galitzine   - Ejecutivo de Ventas Corporativas
--  18  Regé-Jean Page       - Asesor de Ventas a Empresas


-- ---------- 3. Correo en perfiles (para que el admin sepa a quién contactar) ----------
alter table perfiles add column if not exists correo text;
update perfiles p set correo = u.email from auth.users u where u.id = p.id;

create or replace function crear_perfil_nuevo_usuario() returns trigger
language plpgsql security definer set search_path = public as $$
begin
    insert into perfiles (id, nombre, correo) values (new.id, new.raw_user_meta_data ->> 'nombre', new.email);
    return new;
end;
$$;


-- ---------- 4. Solicitudes mayoristas ----------
-- Regla del negocio: cada producto de la solicitud debe tener 12 unidades o más.
create or replace function es_pedido_mayorista(productos jsonb) returns boolean
language sql immutable as $$
    select jsonb_typeof(productos) = 'array'
       and jsonb_array_length(productos) > 0
       and (select bool_and((p ->> 'cantidad')::int >= 12) from jsonb_array_elements(productos) p);
$$;

create table if not exists solicitudes_mayoristas (
    idsolicitud  integer generated by default as identity primary key,
    idusuario    uuid not null default auth.uid() references perfiles(id) on delete cascade,
    idempleado   integer not null references empleados(idempleado),
    productos    jsonb not null check (es_pedido_mayorista(productos)),  -- [{idproducto, nombre, precio, cantidad}]
    mensaje      text check (length(mensaje) <= 500),
    estado       text not null default 'pendiente' check (estado in ('pendiente', 'atendida')),
    fecha        timestamptz not null default now()
);

alter table solicitudes_mayoristas enable row level security;

drop policy if exists "crear mi solicitud"  on solicitudes_mayoristas;
drop policy if exists "ver mis solicitudes" on solicitudes_mayoristas;
drop policy if exists "admin actualiza"     on solicitudes_mayoristas;

-- Un cliente solo puede crear solicitudes a su nombre y solo con un asesor real
create policy "crear mi solicitud" on solicitudes_mayoristas for insert to authenticated
    with check (idusuario = auth.uid()
                and exists (select 1 from empleados e where e.idempleado = solicitudes_mayoristas.idempleado and e.es_asesor));
-- Cada cliente ve las suyas; el admin ve todas
create policy "ver mis solicitudes" on solicitudes_mayoristas for select to authenticated
    using (idusuario = auth.uid() or es_admin());
-- Solo el admin cambia el estado (pendiente / atendida)
create policy "admin actualiza" on solicitudes_mayoristas for update to authenticated
    using (es_admin()) with check (es_admin());

grant select, insert, update on solicitudes_mayoristas to authenticated;
grant usage on all sequences in schema public to authenticated;
